[package]
name = "Numerical-Lib"
version = "0.1.0"
authors = ["Yuhang Ying <yuhang_ying@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packed_simd = "0.3.3"
stopwatch = "0.0.7"
rand = "0.3.17"
time = "0.1"